name: Build and Deploy Docs

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/embedded-lib-dev:latest

  permissions:
    contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Doxygen
        run: doxygen Doxyfile
        working-directory: ./doc

      - name: Build Sphinx HTML
        run: sphinx-build -b html ./source ./build
        working-directory: ./doc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/build
